Added links to config docs
TrossenRobotics/aloha_docs pull request #26
Opened 2024-10-04 16:55 UTC by Shiming-Liang

2024-10-04 19:09 UTC, lukeschmitt-tr requested changes

2024-10-04 19:09 UTC, lukeschmitt-tr commented on docs/operation/bringup_shutdown.rst
> +The configuration yaml files provided in the ``~/interbotix_ws/src/aloha/config`` directory can be used to customize the behavior of the ALOHA.
```suggestion
==============

The configuration yaml files provided in the ``~/interbotix_ws/src/aloha/config`` directory can be used to customize the behavior of the ALOHA.
```

2024-10-04 19:09 UTC, lukeschmitt-tr commented on docs/operation/bringup_shutdown.rst
> +-   Intel RealSense Cameras
Link to the realsense_ros config guide: https://github.com/IntelRealSense/realsense-ros/tree/ros2-development?tab=readme-ov-file#parameters

2024-10-04 19:36 UTC, shantanuparab-tr approved these changes
Looks Good

2024-10-07 15:08 UTC, lukeschmitt-tr approved these changes

2024-10-07 15:08 UTC, merged